apiVersion: v1
kind: Namespace
metadata:
  name: devops-agent
  labels:
    name: devops-agent
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
